### ISSUE TITLE
DEV-8 Favicon: missing favicon

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/React-Highcharts#13]
I forgot to add a favicon to my webpage:

![image](https://user-images.githubusercontent.com/26466644/31635078-e53e85e0-b2c5-11e7-9eaf-0f9d511b0132.png)

I would like to have the icon that is simple but pretty, better if it will have some colors and will be related to charts. Something like this: 

![image](https://user-images.githubusercontent.com/26466644/31635394-db7a57ea-b2c6-11e7-986c-90e096ed36b1.png)

It is not obligatory to use the pictures provided, any ideas are welcome. But only one wish is that before submitting the PR, post here (as a comment with screenshot) the icon that you have chosen and I will give my feedback about it.

To work on this issue, please use a branch with the identifier "DEV-8".

**Comment by TetianaKlymchuk** [comment]
I have choosed  the following choices for the favicon:
![screenshot_2](https://user-images.githubusercontent.com/28005338/31855479-ab03e81e-b6b4-11e7-9ad8-dd02dc06590e.png)
I've already add to the progect the favicon №1. Here is the result:
![screenshot_1](https://user-images.githubusercontent.com/28005338/31855487-d1259c5e-b6b4-11e7-97c3-7aa947c69f72.png)
Please check. Waiting for your feedback.

**Comment by KovDimaY** [comment]
Looks nice! Go ahead and open a pull request! :)

**Comment by KovDimaY** [comment]
Good job! Your changes are deployed to Heroku! You can check it here: https://react-highcharts-practice.herokuapp.com
