### ISSUE TITLE
DEV-10 Description: button with info about current mode

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/React-Highcharts#15]
The issue is very similar to Issue #14 (DEV-9 Export). The idea is to have a button which will open a pop-up window with the info about the current mode of the application. I think it would be great to have such feature because not all the modes are so clear how they work and what configurations suppose to change...

It is not obligatory to have a pop-up, it could be just a tooltip like on the page with Stock Simulation of the Line Page: 
![image](https://user-images.githubusercontent.com/26466644/31636823-5e6ad1b6-b2cc-11e7-8cd7-8d93f9f395b9.png)

But again, the problem is that I do not know where to put the button. I do not want to spoil current layout... The only thing that I want the button to be small with the meaningful icon like this:
![image](https://user-images.githubusercontent.com/26466644/31636903-a349c8f0-b2cc-11e7-8afb-1a347359a085.png)
(better if it will be black)

I would like to ask that before submitting the PR, one posted here (as a comment with screenshot) the layout that one has chosen and I will give my feedback about it.

To work on this issue, please use a branch with the identifier "DEV-10".

**Comment by NikolayYakovenko** [comment]
I think I can do this.

**Comment by KovDimaY** [comment]
Cool, would be great! :D 
Do you have any ideas?

**Comment by NikolayYakovenko** [comment]
Of course.
In my opinion black icon isn't suitable for this menu.
It will looks more clear with icon like this:
![menu](https://user-images.githubusercontent.com/5685784/31862166-5ce24570-b742-11e7-8478-61d4164f3dfc.png)

**Comment by KovDimaY** [comment]
The problem is that the description is needed more for the configs modes:
![image](https://user-images.githubusercontent.com/26466644/31862272-793d9532-b73b-11e7-97f1-cb3f408d049c.png)

because is not always clear what is "Stock Simulation" (or "Pure Random", or "Polynomial Functions"), how it supposed to work and what is the settings of the mode.

So, if we are going to make a tooltip, it should be somehow connected with the current mode of the configurations. If we will put the tooltip on the navbar like you have proposed, it will look more like a description of the Line Chart page in general, that is not really needed because Line means that it is a page dedicated to different modes of Line chart :)

Thank you for the proposal! But we need to think a little bit more about this... I think this issue is not so easy :)

**Comment by NikolayYakovenko** [comment]
Ok. I understand.
In this case I propose create a new simple component Tooltip,  which you can use in any place.
Content for this tooltip will be imported like other data from config. Design or icon you will be able to change.
For this menu we can expand **modes** object adding two new field - title and tooltip:
`const modes = {
  pureRandom: {
    title: "Pure Random",
    tooltip: "Help text is here bla bla bla",
  },`

**Comment by KovDimaY** [comment]
As I understand, you propose to put icons with tooltips near each label of the Configurations, am I right? If yes, I like this idea! It gives the opportunity to add some info, but at the same time, it will be small, compact and laconical. I think it is good to have as little text as it is possible 👍 

Regarding the changes of the modes constant, I do not really like the idea, because it means that we will need to change a lot of code in all the application that can lead to bugs and errors. Also, I want to keep the structure objects as simple as it is possible, so maybe is better to create a new constant for titles, for example: 
`const titles = { 
     pureRandom: "Here is some title for PR", 
     configurableRandom: "Here is some title for PR",
     etc...
};`

**Comment by NikolayYakovenko** [comment]
Here is result. You can define position of tooltip, choose an element that will trigger appearance of tooltip and add some classes.
![tooltip](https://user-images.githubusercontent.com/5685784/31906566-15d62946-b83a-11e7-9b66-135bbef03c2f.png)

**Comment by KovDimaY** [comment]
Looks nice for me! Have you done it for all the implemented modes (Line, Bar, Pie)?

**Comment by NikolayYakovenko** [comment]
No. But I can add for modes you mentioned above.

**Comment by KovDimaY** [comment]
Would be great if you implement it for all the modes. :) 
BTW, I cannot see the branch on which you are working... Are you working on the branch DEV-10? Could you push your commits so I could try your changes?

**Comment by NikolayYakovenko** [comment]
I've pushed my changes.

**Comment by KovDimaY** [comment]
I am watching the code and a result and I like it very much! Good job! 

But also I have found some small details that I would like you to fix before the merging of the PR:
1) Could you add to the tooltip buttons: 
![image](https://user-images.githubusercontent.com/26466644/31964579-c18336ec-b904-11e7-9888-56571b74051d.png)

the same "onClick" function that the drop-down items have? So if the user will click the mode's button which one is reading about, this mode will be running.
2) Could you fix the tooltip position in the case when the screen is the smallest => @media (min-width: 0px). Now it works quite weird, putting tooltip out of the screen:
![image](https://user-images.githubusercontent.com/26466644/31964621-ee54b466-b904-11e7-9261-7099ed14677f.png)

Thank you in advance! :)

**Comment by NikolayYakovenko** [comment]
1. I will do this a little bit later.
2. Done.

**Comment by KovDimaY** [comment]
Is it something difficult to do? Or you just did not have time? I was thinking about just to move the "onClick" function from the `<a>` tag to the parent object `<li>` :
![image](https://user-images.githubusercontent.com/26466644/31985830-a30a05d0-b966-11e7-8f1d-b814a3a05cd7.png)

I think it should solve the problem that I have mentioned :) What do you think?

**Comment by NikolayYakovenko** [comment]
It is not difficult. I didn't have enough time.
Your solution requires changes of `dropdownCkickHandler`.
`dropdownCkickHandler` use innerHTML content of node, this is not good idea, because this text can change in future.
I will try to solve this problem.

**Comment by KovDimaY** [comment]
Yes, you are right! Good point! 👍

**Comment by KovDimaY** [comment]
PR merged, I close the issue
