### ISSUE TITLE
DEV-12 LineChart: missing area chart view

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/React-Highcharts#17]
On the Line Chart page, I have many different modes of a line chart, but I missed to use an "area" representation. Basically, it looks like this: 

![image](https://user-images.githubusercontent.com/26466644/31820417-84380206-b5a1-11e7-82ea-4ea4203f7e4c.png)

As the data format and all other settings are almost the same for the "line" and "area" representation of the charts, I propose to put one more config option (one more checkbox) in the Pure Random mode: 

![image](https://user-images.githubusercontent.com/26466644/31820520-f1bd23f6-b5a1-11e7-8a5d-01f0f7fca467.png)

that gives the user the opportunity to see the chart in "line" or "area" mode for the same generated data.

To solve the issue, you will need to update function **updatePureRandomConfiguration()**: 
![image](https://user-images.githubusercontent.com/26466644/31820679-ab369d12-b5a2-11e7-9314-db7b2f68d6ba.png)

and **renderPureRandomModeConfiguration()**:
![image](https://user-images.githubusercontent.com/26466644/31820718-dd404092-b5a2-11e7-934d-c79cc7b424aa.png)

and do not forget that you need to have all the options to be registered:
![image](https://user-images.githubusercontent.com/26466644/31820772-0aa62c7c-b5a3-11e7-93d7-3dd213ba4b75.png)

For more information about how to implement the feature, visit area chart demo: https://goo.gl/N53vtF

Please, solving this issue is the same file/folder patterns and the same code style.

To work on this issue, please use a branch with the identifier "DEV-12".

**Comment by TetianaKlymchuk** [comment]
Please check obtained result:
![image](https://user-images.githubusercontent.com/28005338/31865796-4357c89c-b77d-11e7-8dbf-861c30bae2ca.png)
Does it look OK?

**Comment by KovDimaY** [comment]
Yes, looks perfect! Create a PR and I will check if everything is implemented correctly :)
Good job! :)
