### ISSUE TITLE
DEV-14 README.md: include project setup info

### ISSUE THREAD

**Issue by TetianaKlymchuk** [KovDimaY/React-Highcharts#19]
It is needed to add the info about the setup of the project. It is not clear which command it is needed to use in order to start the project. Indeed, there is the information about the deployment to Heroku:
![screenshot_1](https://user-images.githubusercontent.com/28005338/31840236-0b79fc10-b5ed-11e7-90f2-5ce763fdeaaf.png)
Please, add the information about the setup in the same way as you did with the deployment.

**Comment by KovDimaY** [comment]
Good point, thank you! Try to figure it out and feel free to add the info to README.md
I will check the result before merge ))

**Comment by TetianaKlymchuk** [comment]
Please, check the result:

![screenshot_2](https://user-images.githubusercontent.com/28005338/31850956-05ca8212-b665-11e7-9f56-7d43684324a9.png)
If you will be satisfied, you can close the issue.

**Comment by KovDimaY** [comment]
Yes, good job! Thank you! :)
