### ISSUE TITLE
DEV-30 Replace links of menu with React-Router links

### ISSUE THREAD

**Issue by aralroca** [KovDimaY/React-Highcharts#58]
Replace normal menu links to React-router links to avoid refreshing the page every time:

     import { Link } from 'react-router-dom'

     <Link to="/about">About</Link>

Ref: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md

**Comment by KovDimaY** [comment]
Yes, you are right! Thank you for the contribution! :D

**Comment by KovDimaY** [comment]
This issue is not resolved due to the errors with the 'react-router-dom':
![image](https://user-images.githubusercontent.com/26466644/38316726-a38a7122-382b-11e8-9857-db5aa6226b66.png)

**Comment by KovDimaY** [comment]
The issue is resolved, merged and deployed.
Everything works as expected. The issue can be closed.
