### ISSUE TITLE
DEV-34 React-Router: nested urls break styles

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/React-Highcharts#66]
All the custom styles for the project are imported through one file in /styles/indes.scss
This file is a kind of entry point for all the styles, to keep them well organized. 
When the user visits the main page or any first-level route, styles are applied correctly and everything works fine. But when the user goes to the url that has more than one nested page, it looks like the path to styles are changing and the project cannot find the styles, so all the styles are broken and the page looks ugly. 
You can see the described behavior on the gif animation attached:
![double message](https://user-images.githubusercontent.com/26466644/40072775-3be1577e-5875-11e8-86cd-fb3cc4de5e5b.gif)

It is good that I do not have nested routs in my application, but I suppose, that if I will want to handle some route of type "/other/boxplot" - it will also break the layout because the css will not be possible to find. I tried to find a solution, but I did not succeed with this, so I need your help.

Comment your ideas under this issue, please, or if you want to try to solve this issue - use a branch **DEV-34** created from the latest master.

Thank you in advance!!! Have a great day!

**Comment by aralroca** [comment]
I think that the problem is not from the sass. Looks more like a problem with external libraries like justified-nav, etc. Isn't it?

In your index.html you are importing the styles using the dot at the beginning. Do you tried to remove this dot?

So;

Instead of:

./styles/...

Use:

/styles/...

**Comment by KovDimaY** [comment]
Great! The issue was resolved in Pull Request #67 by @NikolayYakovenko 
Thank you all for your commitments! 
The PR is merged and the last version is deployed on Heroku. 
The issue can be closed.
