### ISSUE TITLE
DEV-36 Add and apply prettier to the project

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/React-Highcharts#73]
At the moment, the code is controlled by linter and it makes it quite nice and clean. But much better and useful is to have prettier installed as well and configure your editor to prettify your code automatically on save.

You can find more about prettier here: https://prettier.io/

Once prettier is installed, would be good to check all the existing files and apply prettier to all of them so the code becomes more structured and clean.

To work on this issue, please use a branch with the identifier "DEV-33".

**Comment by KovDimaY** [comment]
We forgot to apply the prettier rules. I will work on that.

**Comment by aralroca** [comment]
You should run `npm run format:all` and then do a commit with all the formatted files 😊

**Comment by aralroca** [comment]
I didn't do it to make the review easier

**Comment by KovDimaY** [comment]
The PR is merged!
